### ISSUE TITLE
Error When Omitting the Function Name

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#101]
When omitting the function name in `scar init` the following error arises:
```
Error: Function name 'scar_function' is not valid
```
Either a default name should be created for the function and shown to the user or output a message that clearly specifies that a function name should be chosen by the user.

**Comment by alpegon** [comment]
Done in PR #108 
If the user doesn't specify a name a random name is generated for the function.
Something like: `scar-0465e2af-3938-4311-a601-326d88204bc5`
