### ISSUE TITLE
Input Files Not Retrieved from S3

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#103]
Scenario:
`scar init -s test/test-file-processor.sh -n lambda-event-test-00 -es scar-test ubuntu:16.04`
where test-file-processor.sh is:
```bash
INPUT_DIR="/tmp/$REQUEST_ID"
OUTPUT_DIR="/tmp/$REQUEST_ID/output"
echo "BEGIN: Invoked File Processor. Files available in $INPUT_DIR"
echo "`ls -l $INPUT_DIR`"
echo "Creating output folder in $OUTPUT_DIR"
cp $INPUT_DIR/* $OUTPUT_DIR
echo "END: Invoked File Processor. Files generated in $OUTPUT_DIR"
````
and `scar-test` is an existing bucket.

When uploading a file:
```
aws s3 cp requirements.txt s3://scar-test/input/req5.txt
```
The Lambda function is triggered but the only file found in /tmp/$REQUEST_ID is event.json.

**Comment by alpegon** [comment]
Fixed in PR #105
