### ISSUE TITLE
Problem When Running Docker Image with Volumes Defined

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#119]
When trying to invoke a SCAR function created out of a Docker image that has a VOLUME defined in the Dockerfile, uDocker fails with the following error:

```
Error: invalid volume destination path: {}
```

This is the case of, for example, the [mesosphere/aws-cli](https://hub.docker.com/r/mesosphere/aws-cli/~/dockerfile/) Docker image (see the [corresponding Dockerfile](https://hub.docker.com/r/mesosphere/aws-cli/~/dockerfile/)).

The expected functionality would be to ignore those volumes and start the execution of the container.

**Comment by alpegon** [comment]
Done in PR #125
