### ISSUE TITLE
Improve Automatic Naming Scheme of Lambda Functions

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#128]
When omitting the `-n` parameter in scar init an automatic name is assigned to the Lambda function, such as scar-e7ab473b-9fb8-48ca-a05c-e0e154bc17fb

It would be much convenient to assign a name depending on the Docker Image assigned. Say you want to create a Lambda function to run jess/imagemagick, the Lambda function could be called: scar-jess-imagemagick and if that name is already chosen one could assign scar-jess-imagemagick-01 or just a final random number.

This would simplify invoking `scar run`, since the Lambda function name is required to be known. Also, this would simplify looking for the logs in CloudWatch Logs.

**Comment by alpegon** [comment]
Done in PR #138

**Comment by gmolto** [comment]
Using the following example:

```sh
scar init ubuntu:16.04
``` yields the following error:

```sh
Error: Function name 'scar-ubuntu-16.04' is not valid.
````
Dots are not valid characters and, therefore, should be replaced (for example with hyphens): scar-ubuntu-16-04

**Comment by alpegon** [comment]
Done in PR #151
