### ISSUE TITLE
Couldn't run init

### ISSUE THREAD

**Issue by jibin-tj** [grycap/scar#145]
Hi 
I couldn't run init command as I get the following error
Error: 'Scar' object has no attribute 'check_memo
ry'

This seems to be an issue with the last commit

**Comment by gmolto** [comment]
Hi @jibin-tj,

Thank you for reporting the bug. Indeed this is happening when using the `-m` parameter. 

In the meantime, if you want to change the memory of the Lambda function you can:

1. Create the Lambda function without using the `-m` parameter and then update the memory either from AWS CLI or from the AWS Management Console. 
2. Modify the contents of $HOME/.scar/scar.cfg to change the default value for the memory.  An example of this file is:

```sh
[scar]
lambda_description = Automatically generated lambda function
lambda_memory = 256
lambda_time = 200
lambda_region = us-east-1
lambda_name = scar_function
```
Kind regards,
Germán

**Comment by jibin-tj** [comment]
Thanks for the reply.
Actually when I tried without uaing -m flag, -t flag is also causing error.
When running init without -t and -m,still i am getting the following error

Error initializing lambda function: An error occu
rred (AccessDeniedException) when calling the Cre
ateFunction operation: Cross-account pass role is
 not allowed.

Please help. Thank you.

**Comment by alpegon** [comment]
Hi @jibin-tj I've fixed the issue whit the -t and -m params in PR #146.
The other issue that you are getting looks related to this: https://maxrohde.com/2016/06/27/aws-lambda-cross-account-pass-role-is-not-allowed/
As @gmolto commented above, there is a configuration file called scar.cfg in where you can specify several parameters. One of them is the `lambda_role`. Please try specifying your lambda role in the config file and relaunch the function again.

```
[scar]
lambda_description = Automatically generated lambda function
lambda_memory = 256
lambda_time = 200
lambda_region = us-east-1
lambda_name = scar_function
lambda_role = "arn:aws:iam::2743496549:role/lambda-s3-execution-role"
```

Thanks

**Comment by jibin-tj** [comment]
Thank you. Its now working fine.
