### ISSUE TITLE
Support for Specifying Local Files/Folders to be Included in the Deployment Package

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#178]
Say you have a Java application encapsulated in a JAR package that you want to execute it on AWS Lambda via SCAR.

There is currently no way to include this file as part of the deployment package in SCAR.

We should have a way to specify during `scar init` a local folder (or local file) in order to pack this as part of the deployment package, which will be made available to the Lambda function in `/var/task`. This folder should be made available to the container in that very same path and optionally define an environment variable for user-defined shell-scripts to easily reference a file available there.

**Comment by alpegon** [comment]
Functionality added in PR #214.
You can use the parameter -ep or --extra_payload in combination with a path to tell scar where the libraries are.
Scar copies the files **inside** the specified folder and puts them in the /var/task/ lambda folder.

Right now the container cannot access this folder, so I will keep this issue open.

**Comment by alpegon** [comment]
Done in PR #219.

When the `-ep` parameter is used, the `/var/task` folder is mounted in the container and the environment variable `EXTRA_PAYLOAD=/var/task` is created.
Have in mind that the `/var/task` folder is read only when managing it from the container.

Can be used like this:
`scar init -n test-ep -ep /tmp/libs/ -i ubuntu`
