### ISSUE TITLE
Support Pre-Heating When Initializing a Lambda Function

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#179]
It would be convenient to have in `scar init` a new parameter, say `--preheat` or `-p` in order to _pre-heat_  the Lambda function, i.e., doing a `scar run` in a request-response manner to trigger the caching of the Lambda function. 

Pre-heating a function could also be the default action when using the `-es` parameter, in order to cache the Lambda function before attempting to start processing events coming from S3.

**Comment by alpegon** [comment]
Done in PR #198.
Have in mind that the preheat step can fail if the container is waiting for entry data although it doesn't matter because the container is going to be downloaded anyway
