### ISSUE TITLE
Lambda function not created but shown as created

### ISSUE THREAD

**Issue by shunya-mandal** [grycap/scar#189]
I am trying to use `scar init ` command to create a lambda function. Here's what I have used-

```
Command: $scar init -n test-lambda-scar2 -m 128 -t 300 mangiferaindica/job-handler
Output:
$Function 'test-lambda-scar2' successfully created.
$Log group '/aws/lambda/test-lambda-scar2' successfully created.
```

As you can see the output shows that the functions is created but when I actually check i=on aws console, the function is not created.
What could be the possible causes.

**Comment by gmolto** [comment]
Hi @shunya-mandal,

It could be that the Lambda function was created in a region other than the one you are checking.

The configuration file $HOME/.scar/scar.cfg indicates the region on which the Lambda functions are created:
```
[scar]
lambda_description = SCAR Lambda function
lambda_memory = 256
lambda_time = 300
lambda_region = us-east-1
lambda_role = arn:aws:iam::XXXXX:role/lambda-role
```
Please, let us know if this solves the issue.

**Comment by shunya-mandal** [comment]
Yes it was created in another region.
