### ISSUE TITLE
How to use local container image?

### ISSUE THREAD

**Issue by comsians123** [grycap/scar#196]
How can I use the local container image with SCAR?

**Comment by gmolto** [comment]
Hi @comsians123,

You cannot use a local container image with SCAR, since the deployment package of a Lambda function has a very limited storage constraints.

You can push it to your user account in DockerHub and then reference that image when creating the function with `scar init`.

Cheers.

**Comment by comsians123** [comment]
Can I use private repo on docker hub?

**Comment by gmolto** [comment]
No. Only public repositories at the moment.

**Comment by comsians123** [comment]
Thanks @gmolto :)
