### ISSUE TITLE
Support user-defined container images in the Deployment Package

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#211]
SCAR currently relies on Docker Hub (or an external Docker Registry) to retrieve the Docker images.
It should support the ability to specify the container filesystem (via a tar file, for example) and include it in the Deployment Package.

Benefits:
* The Deployment Package limit is 250 MB. This does not add up to the 500 MB limit of the ephemeral storage so plenty of additional space would be available for the Lambda function.
* Reduced latency
* Support for closed-source algorithms that cannot use a public Docker Hub but still use Docker for application delivery.

**Comment by alpegon** [comment]
After the PR #214 SCAR allows to upload docker images using an S3 bucket.
More information can be found in the **README** section: [Upload docker image files using an S3 bucket](https://github.com/grycap/scar#upload-docker-image-files-using-an-s3-bucket)
