### ISSUE TITLE
Error: command not found or has no execute bit set:

### ISSUE THREAD

**Issue by andrewcretin** [grycap/scar#215]
I am trying to run the docker image from `sourcey/spectacle`, and keep getting this error.

`Error: command not found or has no execute bit set:  ['/bin/sh', '/tmp/76f38398-2ec7-11e8-bf4b-398c60e26074/init_script.sh']`

I am able to deploy to AWS and everything works as expected in regards to the deployment. The s3 buckets are triggering the lambda function as expected. Just no success on the actual execution.

My `create-docs.sh` file looks like this 

```
#! /bin/sh

OUTPUT_DIR="/tmp/$REQUEST_ID/output"

echo "SCRIPT: Invoked Spectacle Doc Maker. File available in $SCAR_INPUT_FILE"
FILENAME=`basename $SCAR_INPUT_FILE`
OUTPUT_FILE=$OUTPUT_DIR/$FILENAME
echo "SCRIPT: Converting .json file $SCAR_INPUT_FILE to spectacle docs in output file $OUTPUT_FILE"
udocker run -it sourcey/spectacle /bin/sh
spectacle $SCAR_INPUT_FILE -f $OUTPUT_FILE 
```

I've seen somethings about having `/bin/busybox` rather than `/bin/sh` but need more clarity on how to fix the issue with that approach

**Comment by gmolto** [comment]
Hi @andrewcretin 

I would check that the [sourcey/spectacle](https://hub.docker.com/r/sourcey/spectacle/) Docker image is not based on Alpine. If so, consider basing the image on debian:stretch-slim.

Cheers,
G.

**Comment by gmolto** [comment]
Also, the script should not run udocker. Your script should be executing directly the executable file inside the Docker image that you would like to use to convert the file. Feel free to ping us if you need further support.

**Comment by jalevin** [comment]
I found a version of alpine that's running on GLIBC instead of MUSL and I'm getting the same error. Do you have any idea why this error occurs on alpine?

**Comment by alpegon** [comment]
Hi, I created an example using spectacle and it's working without issues.
Please, check the example [here](https://github.com/grycap/scar/tree/master/examples/spectacle)
Cheers
