### ISSUE TITLE
Improve documentation to describe the dependence with Python 3

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#227]
Since SCAR requires Python 3 on the client-side to be executed, this should be indicated in the README file as a requirement.

For Linux installations with Python 2.X the following error is obtained:
```
Traceback (most recent call last):
  File "./scar.py", line 18, in <module>
    from src.providers.aws.controller import AWS
ImportError: No module named providers.aws.controller

After installing Python 3, the configuration of SCAR and its requirements is then slightly modified:
```
sudo apt install python3-pip 
pip3 install -r requirements 
alias scar='python3 $SCAR_HOME/scar.py'
```
where SCAR_HOME should be modified accordingly.

**Comment by alpegon** [comment]
Add python3 requirement in PR #251
