### ISSUE TITLE
Support Multiple Credentials via Profiles 

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#233]
AWS CLI supports choosing a specific set of credentials from `$HOME/.aws/credentials` via the `--profile` command-line flag. It would be nice to support that same parameter in SCAR and pass it down the information to Boto to choose the correct credentials.

**Comment by alpegon** [comment]
There is a branch called 'mult-prof' that implements this.
I will merge it later this week.

**Comment by alpegon** [comment]
This functionality is implemented in the PR #258.
You can add the --profile or -pf option to each command to use a profile different than the default one.
It can also be added to the yaml file like this:

functions:
  function-name:
    image: my-image
    profile: my-other-profile
