### ISSUE TITLE
HTTP/Api Gateway Event Sources

### ISSUE THREAD

**Issue by jbellmore** [grycap/scar#234]
First I would like to say thanks for all the hard work the team has done to get Docker running on lambda! This is a very exciting project and could open up a whole world of possibilities for serverless computing, namely running legacy or packaged software where you do not have control over the source and can not make it "cloud native."

I have a question (and possible feature request). I see S3 file events listed as triggers you can set for the lambda functions, but do you currently support any http endpoint triggers via the api gateway or anything else? I would **love** to be able to run some apps that are only available as prepackaged self hosted web applications (installed via apt packages) and think scar would be an awesome way to do this if it does (or could) support http endpoints.

Happy to try to contribute, would likely need a bit of guidance though :)

Thanks again!

**Comment by gmolto** [comment]
Hi @jbellmore,

Thank you for your interest. There is a branch called apigateway precisely for that. It still has not been merged into the master branch because some testing and documentation is still ongoing but this will be sorted out in the coming days.

Regards.

**Comment by jbellmore** [comment]
Excellent, I will take a look at that, thanks!

**Comment by alpegon** [comment]
Hi, sorry for the delay in the response :sweat_smile: 
The API Gateway functionality is currently merged into the main branch, if you find some missing functionality, please let us know.
Also, if you have any use case that you would like to share we could add it to our examples.
Thanks for using SCAR !
