### ISSUE TITLE
API Gateway endpoint query string parameters

### ISSUE THREAD

**Issue by bmallary** [grycap/scar#246]
I have run into a use case where I needed to pass query string parameters passed via and API Gateway endpoint to the executable in the docker container. I have made an update to SCAR to pull these from lambda_instance.event and pass them to the container via environment variables.

I would be interested to know if there are any other approaches to this issue that have worked.

**Comment by alpegon** [comment]
We were not supporting this functionality right now, but, extracting the parameters from the lambda_instance.event['queryStringParameters'] and passing them to the container as environment variables is what we would have done.
In fact, if you want, create a PR with this functionality and we would be happy to accept it.

**Comment by alpegon** [comment]
Done in PR #284
