### ISSUE TITLE
There was an unmanaged exception in prepare_lambda_code

### ISSUE THREAD

**Issue by JohnCoates** [grycap/scar#265]
Running the example from examples/aws-cli
`scar init -f scar-aws-cli.yaml` produces the message `There was an unmanaged exception in prepare_lambda_code` and no other details.

I'm on macOS 10.13.4

**Comment by alpegon** [comment]
Hi, you should have a log file in the folder `~/.scar/` called `scar.log`
Can you post the log file to have more information about the error?

IMPORTANT, check first that your `AWS_ACCESS_KEY_ID` or `AWS_SECRET_ACCESS_KEY` is not present in the log

**Comment by JohnCoates** [comment]
Found the issue: scar/udockerb: cannot execute binary file 

udocker doesn't support macOS, and this is an ELF file

**Comment by alpegon** [comment]
Yep, my bad, I changed the udocker python file to a binary file and now it seems that it doesn't work on macOS.
I'm working on a fix

**Comment by JohnCoates** [comment]
That's great news! Thanks for the heads up

**Comment by alpegon** [comment]
Now it should be working again in macOS. 
Please tell me if you find any other bugs.

Thanks

**Comment by JohnCoates** [comment]
Great, thanks! I'll let you know about a bug in a moment
