### ISSUE TITLE
Unable to execute scar ls command in ubuntu machine, final goal is to execute docker in AWS Lambda env

### ISSUE THREAD

**Issue by tarunkumard** [grycap/scar#341]
Hi,

My end goal is to execute docker image using SCAR in AWS Lambda cloud env, hence I followed the steps mentioned here https://hub.docker.com/r/grycap/dwi-ivim/ 

Then I  have also followed all steps mentioned in installation doc https://scar.readthedocs.io/en/latest/installation.html#install-using-pip3 and I got success for all the steps 
pip3 install -U setuptools
pip3 install scar

But when I try to  execute the scar commands directly like: scar ls

I get below message
ubuntu@ip-172-31-29-248:~/scar/scar$ scar ls
Expecting value: line 1 column 2 (char 1)

Eventually when I try running scar init command I get below error

ubuntu@ip-172-31-29-248:~/scar/scar$ scar init -n lambda-docker-cowsay -m 128 -t 300 grycap/cowsay
Expecting value: line 1 column 2 (char 1)

**Comment by srisco** [comment]
Hello,

seems to be a problem in the installation, maybe related with the python version used. Could you tell me your python3 version by executing `python3 --version`, please?
The content of `.scar/scar.log` file could also be useful to know what's happening.

**Comment by tarunkumard** [comment]
thanks for reaching out,over the weekend i have found other way to use your project by creating a container,thanks for the great project
