### ISSUE TITLE
Why SCAR asking for valid iam role when I have provided valid lambda_role in /home/ubuntu/.scar ?

### ISSUE THREAD

**Issue by tarunkumard** [grycap/scar#342]
Now I tried creating a scar container based on https://scar.readthedocs.io/en/latest/scar_container.html

Now the SCAR container says
User: arn:aws:iam::825251119036:user/mcbook is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:825251119036:function:scar-cowsay

Here is my scar.cfg file ,should I need to set any other role here?
[scar]
lambda_description = SRE Lambda function
lambda_memory = 256
lambda_time = 200
lambda_region = us-west-2
lambda_role = arn:aws:iam::825251119036:user/mcbook
lambda_timeout_threshold = 10

But it seems the SCAR container expects some other lambda_role value ..I am passing scar.cfg value using /home/ubuntu/.scar

Here is my permission json details assigned to user "mcbook" in json format
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:*"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::*"
        }
    ]
}

here is my docker run command and local host folders mounted as shown below👍
sudo docker run -it -v $AWS_CREDENTIALS_FOLDER:/home/ubuntu/.aws -v $SCAR_CONFIG_FOLDER:/home/ubuntu/.scar scar  

Here is the log details after the image is created and scar run command says exception in invoke function

ubuntu@ip-172-31-29-248:~/scar$ sudo docker run -it -v $AWS_CREDENTIALS_FOLDER:/home/ubuntu/.aws -v $SCAR_CONFIG_FOLDER:/home/ubuntu/.scar scar
~ $ scar init -n scar-cowsay -i grycap/cowsay
Config file '/home/scar/.scar/scar.cfg' created.
Please, set a valid iam role in the file field 'role' before the first execution.
~ $ scar run -n scar-cowsay
There was an exception in invoke_function
User: arn:aws:iam::825251119036:user/mcbook is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:825251119036:function:scar-cowsay~ $ 

Could you please help in finding which lambda_role is needed for scar run?

**Comment by srisco** [comment]
Hi @tarunkumard! Thank you for using SCAR. I noticed from #341 that you're following the steps from https://hub.docker.com/r/grycap/dwi-ivim/. That readme is very outdated and the config file you're defining don't work in newer releases of SCAR, the current one have this format: https://scar.readthedocs.io/en/latest/configuration.html#configuration-file.

Please try configuring SCAR with it and let me know if you have any other issue.

Cheers.

**Comment by tarunkumard** [comment]
thanks for reaching out,over the weekend i have found other way to use your project by creating a container,thanks for the great project
