### ISSUE TITLE
My docker image is 396MB which is <512MB still AWS cloud watch fails to execute saying No SPACE LEFT

### ISSUE THREAD

**Issue by tarunkumard** [grycap/scar#344]
Hi My docker image size is 396MB using maven:3.6.3-ibmjava-8-alpine ,still after running my function using scar aws cloud watch says No space left on device,what should i do? any suggestion idea or solution

here is aws could watch logs
2020-02-25

01:51:24
START RequestId: e8eab1ff-eb5c-4d56-9be5-324364358338 Version: $LATEST

01:51:24
2020-02-25 01:51:24,639 - supervisor - INFO - Reading storage configuration

01:51:24
2020-02-25 01:51:24,667 - supervisor - WARNING - There is no output defined for this function.

01:51:24
2020-02-25 01:51:24,685 - supervisor - WARNING - There is no storage provider defined for this function.

01:51:24
2020-02-25 01:51:24,685 - supervisor - INFO - SUPERVISOR: Initializing AWS Lambda supervisor

01:51:24
2020-02-25 01:51:24,730 - supervisor - INFO - Found 'LOCAL' input provider

01:51:24
2020-02-25 01:51:24,730 - supervisor - INFO - INPUT_FILE_PATH variable set to '/tmp/tmp_m202pzz/event-file-eca624a3-76b4-418a-bac5-35e223b7a82b'

01:51:25
2020-02-25 01:51:25,289 - supervisor - INFO - Pulling container 'tarunkumard/selfserviceload1.0' from Docker Hub

01:51:46
Downloading layer: sha256:4167d3e149762ea326c26fc2fd4e36fdeb7d4e639408ad30f37b8f25ac285a98

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:56dae0f47127209aea70646977ebe366124ed65f82542cf651f109356bff110b

01:51:46
Downloading layer: sha256:b5fad1ca64c34cb5644888bf2c8ae8fee9a4b1c9437b10bf8c0242dc13ce232a

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:4caa3d42c822b52e4a611f05d8ab9025fc59ce84b59e8d348f9e5071ea1d8d84

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:e3d3e01a368c0532b69601c4eb13daab81df506b81064e99adbbe2c803e22ea7

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:4988c549342b31ca6e407ea34304b4a4a8054860c47b9949c3cc25438a46d9cb

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:c4c723d0d4eba1cf0a482bac13a8391c581a7b0f60e7e270f3207e2968cd006e

01:51:46
Downloading layer: sha256:ac86fde823eeda2ede21c0b541d8ec9c309ef622d488703589a1685710b63360

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:a2ebb075261e2f47c85f4b1a2a1cf71d51c39064a6b3bcc636380d878495af85

01:51:46
Downloading layer: sha256:b8dd827cd6e4bccba3f1684e8a2b9492460c3b164e8ed0c5c7946398f18b04d1

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Downloading layer: sha256:2200f5f24a877be33454e52ac6488335e1e43024a7f30641903075ebf7c58d50

01:51:46
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4

01:51:46
Info: creating repo: /tmp/shared/udocker

01:51:46
2020-02-25 01:51:46,748 - supervisor - INFO - Creating container based on image 'tarunkumard/selfserviceload1.0'.

01:52:16
Info: creating repo: /tmp/shared/udocker

01:52:16
9503f5dd-79ea-3b06-aeb7-968f85491645

01:52:16
Info: creating repo: /tmp/shared/udocker

01:52:16
Traceback (most recent call last):

01:52:16
File "/opt/udocker/udocker.py", line 7154, in <module>

01:52:16
sys.exit(Main().start())

01:52:16
File "/opt/udocker/udocker.py", line 7142, in start

01:52:16
exit_status = self.execute()

01:52:16
File "/opt/udocker/udocker.py", line 7125, in execute

01:52:16
status = cmds[command](self.cmdp) # executes the command

01:52:16
File "/opt/udocker/udocker.py", line 6752, in do_setup

01:52:16
return exec_mode.set_mode(xmode.upper(), force)

01:52:16
File "/opt/udocker/udocker.py", line 3676, in set_mode

01:52:16
and elfpatcher.get_ld_libdirs(force))

01:52:16
File "/opt/udocker/udocker.py", line 1654, in get_ld_libdirs

01:52:16
FileUtil(self._container_ld_libdirs).putdata(ld_str)

01:52:16
File "/opt/udocker/udocker.py", line 985, in putdata

01:52:16
filep.close()

01:52:16
OSError: [Errno 28] No space left on device

01:52:17
2020-02-25 01:52:17,065 - supervisor - INFO - Executing udocker container. Timeout set to '237' seconds

01:52:17
2020-02-25 01:52:17,615 - supervisor - INFO - Searching for files to upload in folder '/tmp/tmpexq81mrr'

01:52:17
2020-02-25 01:52:17,615 - supervisor - INFO - Creating response

01:52:17
END RequestId: e8eab1ff-eb5c-4d56-9be5-324364358338

01:52:17
REPORT RequestId: e8eab1ff-eb5c-4d56-9be5-324364358338 Duration: 52985.76 ms Billed Duration: 53000 ms Memory Size: 5

**Comment by srisco** [comment]
Hello, as it says in https://scar.readthedocs.io/en/latest/limitations.html

> The Docker container must fit within the current AWS Lambda limits:
> - **Compressed + uncompressed** Docker image under 512 MB (udocker needs to download the image before uncompressing it).

Anyway, I recommend you to test the [batch execution mode](https://scar.readthedocs.io/en/latest/batch.html) of SCAR, that allows bigger images and/or longer timeouts.

Cheers.

**Comment by tarunkumard** [comment]
thanks
