### ISSUE TITLE
Scar unable to execute AWS Lambda function using Uploaded Docker image to S3 

### ISSUE THREAD

**Issue by tarunkumard** [grycap/scar#345]
Hi ,
Based on https://scar.readthedocs.io/en/latest/advanced_usage.html i have created a yaml with below contents and saved the image on S3 inbucket named "zipforsre" and made that bucket "zipforsre" as public,what is wrong i am doing here?

Save docker image and upload to S3 using below commands
docker images 
sudo docker save tarunkumard/selfserviceload1.0 | gzip > selfserviceload1.0_latest.tar.gz 

Scar command failed with below reason

~ $ scar init -f SRE-BlackBoxTester.yaml
Using existent 'faas-supervisor' layer.
Error: image file does not exist: selfserviceload1.0_latest.tar.gz
Error: loading failed
Command '['python3', '/tmp/tmp3c5o_9sl/udocker/udocker.py', 'load', '-i', 'selfserviceload1.0_latest.tar.gz']' returned non-zero exit status 1.

Why scar saying image file does not exist when i have manually uploaded the docker image file?

Here is my yaml 👍 

~ $ vi SRE-BlackBoxTester.yaml 

functions:
  aws:
  - lambda:
      name: SREBlackBoxTester
      container:
        image_file: selfserviceload1.0_latest.tar.gz
      deployment:
        bucket: zipforsre
~

**Comment by srisco** [comment]
Hi, `scar init` command uploads the image file specified when creating the function, it don't allow uploading images manually. In this case the error appears because the file is not present in your current directory. Remember that the maximum size for the deployment package is an unzipped file of 250MB.

**Comment by tarunkumard** [comment]
thanks for the info
