### ISSUE TITLE
How can i schedule scar run -n   <Function name>

### ISSUE THREAD

**Issue by tarunkumard** [grycap/scar#347]
Hey there,

Could you hep me in finding a a way where i need to invoke the lambda function created a part of scar init -f sre.yaml to be executed or run at scheduled intervals ?

any ideas ?

Also as of now the only was i am running scar project is going inside container  using below commands 
sudo docker build -t scar -f Dockerfile . 
docker run -it -v $AWS_CREDENTIALS_FOLDER:/home/scar/.aws -v $SCAR_CONFIG_FOLDER:/home/scar/.scar scar 

But as you already know this isnt the idle way in productioni need a automated way to run these lambda function invocations?

**Comment by srisco** [comment]
Hello,

What you propose can be done by creating a CloudWatch event to trigger your Lambda function. At the moment SCAR don't allow to define CloudWatch events in the config (but we plan to implement it #320). However, you can create it manually (see https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/RunLambdaSchedule.html).

Hope it's helpful.

Cheers.

**Comment by tarunkumard** [comment]
offcourse its useful ,thanks a ton
