### ISSUE TITLE
Scar local, does not honour env variables

### ISSUE THREAD

**Issue by WinstonN** [grycap/scar#354]
Hi

I was running scar with this command

```
python3 scar/scarcli.py init -n scar-cowsay -i grycap/cowsay
```
As explained in the docs here: https://scar.readthedocs.io/en/latest/installation.html#clone-the-github-repository step 3

I noticed I got the error:
```
❯❯❯ python3 scar/scarcli.py init -n scar-cowsay -i grycap/cowsay
Error getting the AWS user information.
Unable to locate credentials.
```

When I finally figured out the script is looking for the config from here:
```
~/.scar/scar.cfg
```

I have this env config set:
```
AWS_CREDENTIALS_FOLDER=/Users/WinstonN/.aws/
SCAR_CONFIG_FOLDER=/Users/WinstonN/Projects/private/scar/config/project-scar-config
```

I think it could make sense if this env is followed. I'll see if I can make a PR but I am only starting with scar, and as it is, I have not even gotten it to run yet :(
Just errors so far.

I have some questions
1. Am I doing something wrong?
2. Is the project still under development?

**Comment by srisco** [comment]
Hello,

sorry for the confusion, the environment variables you mention are set in the docs to indicate the absolute path of the scar configuration folder to be mounted on the container. As you say, currently scar does not allow to indicate the path of the configuration folder through environment variables, however I see no problem in adding that functionality.

Thanks for the PR!

**Comment by srisco** [comment]
#355 Merged and released

**Comment by WinstonN** [comment]
@srisco Thank you for the explanation - really appreciate that
NP with the PR, I tried to keep it clean
