### ISSUE TITLE
S3 storage not working with user-defined scripts

### ISSUE THREAD

**Issue by mrconrui** [grycap/scar#373]
I've run into an issue when trying to pass a user-defined script to a SCAR function that uses S3 buckets for IO storage. It happens using either the -s flag or the run_script field in the YAML file. It looks like the script runs fine (or that is what it looks like in the CloudWatch logs) but no result is stored in the output bucket. When using the init_script field in the YAML file, it does work as expected (tried with the imagemagick example and my own custom YAML).

I'm not sure where the problem is, maybe I'm misinterpreting something in the documentation. Any help is appreciated. 

Thanks!

**Comment by srisco** [comment]
Hi @mrconrui, can you provide more info about your use-case? I just checked it and should works properly, are you storing the result files of the `run_script` into the `$TMP_OUTPUT_DIR` folder?

**Comment by mrconrui** [comment]
Hi @srisco, I've cloned the script and YAML from the imagemagick example, just changing the S3 bucket paths in the YAML, but the script is left unchanged, and as I said, using the init_script field in the YAML works completely fine. Let me try one more time and if it still doesn't work I'll email you the files.
