### ISSUE TITLE
Docker images with ENTRYPOINT cannot be used to run user-defined shell-scripts

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#60]
Docker images created out of Dockerfiles with an ENTRYPOINT cannot be employed to run a shell-script with SCAR.

udocker's `-nometa` parameter could be used to be able to achieve it:

```
udocker run --nometa -e AWS_ACCESS_KEY_ID=<AK> -e AWS_SECRET_ACCESS_KEY=<SK> $IMG_CONT_NAME /usr/local/bin/python /usr/local/bin/aws ec2 describe-instances
```
But that option prevents from volumes being mounted on the container.

Options: 
1. Modify uDocker to support overriding the entrypoint and push the changes upstream.
2. Create specific images without ENTRYPOINT

**Comment by alpegon** [comment]
Done in PR #89

**Comment by gmolto** [comment]
I tried to create a Lambda function out of a Docker image with entrypoint:
```
scar init -p examples/aws-cli/event-processor.sh -n lambda-aws-cli-events grycap/aws-cli
```
However, running the function results in the entrypoint being executed:
```
scar run lambda-aws-cli-events
```
The expected behaviour would be to actually execute the event-processor.sh script. Reopening this issue.

**Comment by alpegon** [comment]
Update the code in PR #90

**Comment by gmolto** [comment]
Tested. Thanks.
