### ISSUE TITLE
Define S3 as a Source of Events to a Lambda Function

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#78]
It would be convenient to define an S3 bucket as a source of events to invoke the Lambda function. 

From the CLI one can achieve this vía:

aws s3api put-bucket-notification-configuration --bucket scar-data --notification-configuration file://notif-config.json

Where the file is:
```
{
   "LambdaFunctionConfigurations": [
 {
     "Id": "scar-bucket-configuration",
     "LambdaFunctionArn": "arn:aws:lambda:us-east-1:974349055189:function:<lambda-function>",
     "Events": [
        "s3:ObjectCreated:*"
     ],
     "Filter": {
        "Key": {
            "FilterRules": [
                {
                   "Name": "prefix",
                   "Value": "input/"
                }
            ]
        }
     }
 }
]
}
```
Similar functionality can be achieved from Boto3 using: https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.put_bucket_notification_configuration

This functionality will easily achieve a mechanism to upload a file to a bucket (into the input folder) and trigger the execution of the Lambda function which will in turn execute the container.

**Comment by alpegon** [comment]
Done in PR #92
