### ISSUE TITLE
Allow Specifying a Shell-Script During Init

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#83]
The `scar init` function should also support the `-p` option, as in `scar run`. This would allow specifying a shell-script that would be executed anytime that the Lambda function is invoked.

The shell-script could be uploaded in the deployment package and an environment variable should be defined so that SCAR Supervisor knows that this shell-script has to be executed upon each invocation. 

This will be useful when using for example S3 as a source events, in order to use a shell-script to manage the events triggered.

**Comment by alpegon** [comment]
Done in PR #87
