### ISSUE TITLE
Pass Down the IAM Credentials to the Containers 

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#97]
The Lambda function has credentials granted from the IAM role to interact with other AWS services.
These credentials should be made available to the underlying executed container (for example as the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY) so that the code running in the container (say AWS CLI) can use these credentials to interact with other AWS services.

**Comment by gmolto** [comment]
In the Lambda execution environment, the following variables are automatically defined:
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN
AWS_SECURITY_TOKEN

These stand for the the temporary security credentials. These environment variables should be passed down to the underlying container *UNLESS* the user defines already values for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY using the `-e` parameter either on `scar init` or in `scar run`.

**Comment by gmolto** [comment]
This is no longer required if solving #98

**Comment by alpegon** [comment]
Done in PR #107
