### ISSUE TITLE
Manage the Input and Output Files in S3 Event from the Lambda Function

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#98]
In order to support the use cases where command-line applications retrieve and upload data from S3 into the execution environment, the AWS CLI should be made available inside the deployment package and, in turn, made it available to the container so that `aws` commands can be properly used, in conjunction with the credentials defined in the environment variables. 

This would require having installed Python, unless the `aws` tool from Tim Kay is integrated (which btw requires perl).

**Comment by gmolto** [comment]
Alternative workflow: Have the Lambda function (scarsupervisor) download the file into /tmp/<request_id>/input so that the container just focus on the processing of the file. After the execution of the container, have the Lambda function upload the file(s) available in /tmp/<request_id>/output

**Comment by alpegon** [comment]
Done in PR #99

**Comment by gmolto** [comment]
Successfully tested.
